### PR TITLE
DRAFT: split dlc schema into train, model, pose

### PR DESCRIPTION
**Pull request by CBroz1**
WIP. Does this split of schema roles work for you, @ttngu207? If so, I'll update documentation to reflect the split.

See corresponding [workflow PR](https://github.com/CBroz1/workflow-deeplabcut/pull/2), specifically the [pipeline](https://github.com/CBroz1/workflow-deeplabcut/blob/dev/workflow_deeplabcut/pipeline.py) which now includes VideoRecording.

forthcoming updates:
- Attempt full workflow usage, resolve issues with pieces that connect schemas.
- documentation for usage, including upstream dependencies

### CODE REVIEW

**Review by ttngu207 — COMMENTED** [review]
I think the split should be into two modules
+ model and pose-estimation 
+ model training (which must import the other module)

I think `model` and `pose-estimation` should really go together, it wouldn't be much of a `deeplabcut` element with just `model`

**Comment by CBroz1** [comment]
My motivation for splitting `model` and `pose` was the imagined use-case where there is only one model. A user could supply their own model table with only the `project_path` field and pose estimation would still function the same. 

I expect...
1. Every user will want to do pose estimation and therefore use the `pose` schema
2. A subset will want to also do model evaluation and therefore need the full `model` schema 
3. A further subset will also want to launch training and therefore use all 3

In the ultimate version of this schema, will we still support the current 'run from on-disk files' process? Or will we want to push users away from that standard? If the former, it seems to me like 'only use the schema you need' is within the a-la-carte design philosophy of the elements.

**Comment by ttngu207** [comment]
The way the `pose` and `model` is implemented here is quite interconnected. I.e. to use `pose`, users must use our `model`, I'm not sure if they can just import and use `pose` by supplying their own model table and the pose estimation step can work.

**Comment by CBroz1** [comment]
oh - you're right. I previously though that we only relied on `project_path`, but I took another look at `do_pose_estimation` where we require the model table to have `shuffle`, `trainingsetindex`, and `model_prefix` - I'll revert to 2 schemas and request your review when complete

**Pull request merged**
